eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: 'false'
    fetch-registry: 'false'
  server:
    renewal-percent-threshold: 0.85

server:
  port: 8761

management:
  endpoints:
    web:
      exposure:
        include: '*'
