spring:
  application:
    name: product-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/products

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 0
