spring:
  application:
    name: product-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/products


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
