spring:
  application:
    name: product-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/products
  zipkin:
    base-url: http://localhost:9411/
    enabled: true
    locator:
      discovery:
        enabled: true
  sleuth:
    sampler:
      probability: 1.0
  cloud:
    compatibility-verifier:
      enabled: false
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka/

server:
  port: 0

management:
  tracing:
    sampling:
      probability: 1.0
