spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/inventories
    username: postgres
    password: root
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create-drop
    show-sql: true
server:
  port: 8082